#!/bin/bash

# setup_database
# Config creation script for folio-mods. Needs the module name as parameter 1


# ================================= Copyright =================================
# Version 0.3.1 (2020-11-10), Copyright (C) 2020
# Author: Jo Drexl (johannes.drexl@lrz.de) for FOLIO
# Coauthors: -

#   This file is part of the LRZ FOLIO debian package

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#   On Debian systems, the full text of the Apache License version 2.0
#   can be found in the file 
#     `/usr/share/common-licenses/Apache-2.0'


# ================================= Variables =================================

# Path of the config directories
FM_CONFPATH="/etc/folio"

# Name of the config file
FM_CONFFILE="dbcredentials.env"

# Path to a file which contains pg_hba.conf style allow rules to import
# This file is created by meta packages to ease setups and will only be written
# to if it's already existing
FM_PGHBACONF="/tmp/folio_pg_hba.conf"

# Path to the directory that indicates automated install
FM_AUTOSETUP_DIR="/tmp/folio_autosetup"
# Autosetup file that contains the prefix for users and databases
FM_AUTOSETUP_PREFIXES="db_prefixes"
# Path to a server settings file
FM_AUTOSETUP_PGSERVER="db_server"
# Path to a DB superuser credentials file; empty if DB setup is to be skipped
FM_AUTOSETUP_PGSETUP="db_setup"


# ================================= Functions =================================

# Exit on cancel
fm_cancel() {
  # Takes no parameters
  # Exits the script
  
  export NEWT_COLORS='root=,red'
  whiptail --title "$FM_HEADLINE - Abort" --msgbox \
    "Abort by user." 8 78
  exit 0
}

# Ask for individual module config options
fm_askconf() {
  # Takes no parameters
  # Returns 0
  
  # Database name
  FM_PGDATABASE=""
  while [ "$FM_PGDATABASE" = "" ]
    do
      if ! FM_PGDATABASE=$(whiptail --title "$FM_HEADLINE - PostgreSQL setup" \
        --inputbox "Provide postgres database name (mind allowed characters):" \
        8 78 $FM_PGDATABASE_DEFAULT 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Can't check this
    done
  # User
  FM_PGUSER=""
  while [ "$FM_PGUSER" = "" ]
    do
      if ! FM_PGUSER=$(whiptail --title "$FM_HEADLINE - PostgreSQL setup" \
        --inputbox "Provide postgres username (mind allowed characters):" \
        8 78 $FM_PGUSER_DEFAULT 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Can't check this
    done
  # Password
  if ! FM_PGPASSWD=$(whiptail --title "$FM_HEADLINE - PostgreSQL setup" \
    --passwordbox "Provide postgres password. Leaving it empty will result in a random string to be used." \
    8 78 3>&1 1>&2 2>&3)
    then
      fm_cancel
  fi
}

# Ask for prefixes (on automatic install)
fm_askprefix() {
  # Takes no parameters
  # Returns 0
  
  # Database prefix
  while [ "$FM_PGDBPREFIX" = "" ]
    do
      if ! FM_PGDBPREFIX=$(whiptail --title "$FM_HEADLINE - Automated PostgreSQL setup" \
        --inputbox "Provide postgres database prefix for all modules (mind allowed characters):" \
        8 78 folio 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Can't check this
    done
  # User prefix
  while [ "$FM_PGUSERPREFIX" = "" ]
    do
      if ! FM_PGUSERPREFIX=$(whiptail --title "$FM_HEADLINE - Automated PostgreSQL setup" \
        --inputbox "Provide postgres username prefix for all modules (mind allowed characters):" \
        8 78 "$FM_PGDBPREFIX" 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Can't check this
    done
    
  # Write the prefix file
  echo -e "FM_PGDBPREFIX=\"$FM_PGDBPREFIX\"\nFM_PGUSERPREFIX=\"$FM_PGUSERPREFIX\"" > "$FM_AUTOSETUP_PREFIXES"

  return 0
}

# Ask for the postgres server
fm_askserver() {
  # Takes no parameters
  # Returns 0
  
  # Server
  FM_PGSERVER=""
  while [ "$FM_PGSERVER" = "" ]
    do
      if ! FM_PGSERVER=$(whiptail --title "$FM_HEADLINE - PostgreSQL setup" \
        --inputbox "Provide postgres server address:" \
        8 78 $FM_PGSERVER_DEFAULT 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Can't really check this
    done
  # Port
  FM_PGPORT=""
  while [ "$FM_PGPORT" = "" ]
    do
      # Ask user
      if ! FM_PGPORT=$(whiptail --title "$FM_HEADLINE - PostgreSQL setup" \
        --inputbox "Provide postgres server port:" \
        8 78 $FM_PGPORT_DEFAULT 3>&1 1>&2 2>&3)
        then
          fm_cancel
      fi
      # Check if number is too big or NAN
      if ! [[ "$FM_PGPORT" =~ ^[0-9]{1,5}$ ]]
        then
          FM_PGPORT=""
      # Check if number is conflicting with ephemeral port range
      elif [ "$FM_PGPORT" -ge "32768" ]
        then
          FM_PGPORT=""
      fi
    done
    
  # Write server settings to file if automated setup is performed
  if [ "$FM_AUTOMATIC" = "1" ]
    then
      echo -e "FM_PGSERVER=\"$FM_PGSERVER\"\nFM_PGPORT=\"$FM_PGPORT\"" > "$FM_AUTOSETUP_PGSERVER"
  fi
}

# Ask if server setup should be done, and if so, for the superuser credentials
fm_askserversetup() {
  # Takes no parameters
  # Returns 0
  
  # Create autosetup file, if such is to be performed
  if [ "$FM_AUTOMATIC" = "1" ]
    then
      touch "$FM_AUTOSETUP_PGSETUP"
      chmod 600 "$FM_AUTOSETUP_PGSETUP"
  fi

  # General question if database is to be prepared
  if ! whiptail --title "$FM_HEADLINE - PostgreSQL server setup" --yesno \
    "Set up PostgreSQL server now?" 8 78
    then
      fm_pgcancel
  fi
      
  # Ask for superuser credentials
  while true
    do
      # Superuser name
      if ! FM_PGSUNAME=$(whiptail --title "$FM_HEADLINE - PostgreSQL server setup" \
        --inputbox "Provide postgres superuser name:" \
        8 78 3>&1 1>&2 2>&3)
        then
          fm_pgcancel
          return 0
      fi
      # Superuser password
      if ! FM_PGSUPASSWD=$(whiptail --title "$FM_HEADLINE - PostgreSQL server setup" \
        --passwordbox "Provide postgres superuser password:" \
        8 78 3>&1 1>&2 2>&3)
        then
          fm_pgcancel
          return 0
      fi
      # Test credentials
      # This query fails when not done by a superuser account, because it
      # prints the connection limits from a superuser only table
      export PGCONNECT_TIMEOUT=5
      export PGPASSWORD="$FM_PGSUPASSWD"
      if psql -h "$FM_PGSERVER" -p "$FM_PGPORT" -U "$FM_PGSUNAME" -c 'SELECT rolconnlimit FROM pg_authid;' postgres > /dev/null 2>&1
        then
          break
        else
          export NEWT_COLORS='root=,red'
          whiptail --title "$FM_HEADLINE - Failure!" --msgbox \
            "Wrong superuser credentials or server not responding. Please try again." \
            8 78
          export NEWT_COLORS=""
      fi
    done
  
  # Write credentials to file if automated setup is performed
  if [ "$FM_AUTOMATIC" = "1" ]
    then
      echo -e "FM_PGSUNAME=\"$FM_PGSUNAME\"\nFM_PGSUPASSWD=\"$FM_PGSUPASSWD\"" > "$FM_AUTOSETUP_PGSETUP"
  fi
  
  return 0
}

# Exit on cancel during PostgreSQL setup
fm_pgcancel() {
  # Takes no parameters
  # Sets FM_NOSETUP
  # Returns 0
  
  # Global variables
  FM_NOSETUP="1"
  
  export NEWT_COLORS='root=,red'
  whiptail --title "$FM_HEADLINE - Abort" --msgbox \
    "Abort by user. Please setup your postgres server manually." 8 78
  export NEWT_COLORS=""
  return 0
}

# Setup the server with user and database
fm_serversetup() {
  # Takes no parameters
  # Returns 0 on success
  # Returns 1 on failure
    
  # Prepare the temporary commands file
  touch "$FM_TEMP"
  chown root:root "$FM_TEMP"
  chmod 600 "$FM_TEMP"
  # Secure the password for the user, so it can't leak on chatty PostgreSQL 
  # server logs
  # The password in PostgreSQL is stored like this:
  # md5passwd = "md5"+md5(cleartxtpasswd+user);
  # This won't work that easy with SCRAM-SHA-256, sadly
  FM_MD5SUM=$(echo -n "$FM_PGPASSWD$FM_PGUSER" | md5sum)
  echo -e "CREATE ROLE $FM_PGUSER WITH PASSWORD 'md5${FM_MD5SUM:0:-3}' LOGIN;\nCREATE DATABASE $FM_PGDATABASE WITH OWNER $FM_PGUSER;" > "$FM_TEMP"
  # Set psql environment
  export PGCONNECT_TIMEOUT=5
  export PGPASSWORD="$FM_PGSUPASSWD"
  # Run psql to create user and database
  echo "Connecting to '$FM_PGSERVER' to install user and database for $FM_PACKAGE..."
  if psql -h "$FM_PGSERVER" -p "$FM_PGPORT" -U "$FM_PGSUNAME" -f "$FM_TEMP" postgres > /dev/null 2>&1
    then
      echo "Done."
      return 0
    else
      return 1
  fi
}


# =============================== Prerequisites ===============================

# We're setting the path variable anew because some systems have that wrong
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Get script location
OS_SCRIPT="${BASH_SOURCE[0]}"

# Check if being root
if [ "$(whoami)" != "root" ]
  then
    echo "$OS_SCRIPT has to be invocated as root!"
    exit 1
fi

# Get parameters
FM_PACKAGE="$1"

# Check mandatory parameter
if [ "$FM_PACKAGE" = "" ]
  then
    echo -e "\nNo package was given, no setup will be performed."
    echo "Usage: setup_database <package>"
    exit 1
fi
# Rework package name to avoid hyphens in database names, which require special
# treatment when used. We use underscores instead
FM_PGPKGNAME="$(echo "$FM_PACKAGE" | tr "-" "_")"

# Set variables & absolute paths
FM_CONFIG="$FM_CONFPATH/$FM_PACKAGE/$FM_CONFFILE"
FM_TEMP="/tmp/setup_database-$FM_PACKAGE-$$"
FM_AUTOSETUP_PGSERVER="$FM_AUTOSETUP_DIR/$FM_AUTOSETUP_PGSERVER"
FM_AUTOSETUP_PGSETUP="$FM_AUTOSETUP_DIR/$FM_AUTOSETUP_PGSETUP"
FM_AUTOSETUP_PREFIXES="$FM_AUTOSETUP_DIR/$FM_AUTOSETUP_PREFIXES"

# Check for automated install
if [ -d "$FM_AUTOSETUP_DIR" ]
  then
    FM_AUTOMATIC="1"
fi

# Check if there's already a config
if [ -f "$FM_CONFIG" ]
  then
    # On automated installs use the config and don't change anything
    if [ "$FM_AUTOMATIC" = "1" ]
      then
        echo "Config for $FM_PACKAGE found."
        exit 0
    fi
    # Otherwise ask if it is to be overwritten
    if ! whiptail --title "$FM_PACKAGE - Config" --defaultno \
      --yesno "Overwrite existing config with new settings?" 8 78
      then
        echo -e "\nConfig found, skipping setup."
        exit 0
    fi
fi

# If no server information file exists, try to extract information about the
# defaults (to ease upgrade and further setups)
if [ ! -f "$FM_AUTOSETUP_PGSERVER" ]
  then
    # Manual installation
    # Try to be clever and check if there is already a folio module config file
    # which can tell us about the server
    FM_MODCONF=$(ls -1 "$FM_CONFPATH"/mod_*/"$FM_CONFFILE" 2>/dev/null | head -n 1)
    if [ "$FM_MODCONF" != "" ]
      then
        # Recheck if it's really a file there
        if [ -f "$FM_MODCONF" ]
          then
            # Source it and set the relevant variables as they would appear in 
            # FM_PGSERVERFILE
            . "$FM_MODCONF"
            FM_PGSERVER_DEFAULT="$DB_HOST"
            FM_PGPORT_DEFAULT="$DB_PORT"
        fi
    fi
fi
# Set server connection defaults (will preserve found ones from above)
FM_PGSERVER_DEFAULT="${FM_PGSERVER_DEFAULT:-localhost}"
FM_PGPORT_DEFAULT="${FM_PGPORT_DEFAULT:-5432}"
    

# =================================== Main ====================================

# Handle automated install
if [ "$FM_AUTOMATIC" = "1" ]
  then
    # Set all variables
    FM_HEADLINE="Folio modules"
    FM_NOSETUP=""
    FM_PGDBPREFIX=""
    FM_PGUSERPREFIX=""
    FM_PGSERVER=""
    FM_PGPORT=""
    FM_PGPASSWD=""
    FM_PGSUNAME=""
    FM_PGSUPASSWD=""
    
    # Ask for prefixes and create prefix file, if necessary
    if [ ! -f "$FM_AUTOSETUP_PREFIXES" ]
      then
        fm_askprefix
    fi
    # Ask for server information and create the file, if necessary
    if [ ! -f "$FM_AUTOSETUP_PGSERVER" ]
      then
        fm_askserver
    fi
    # Ask for setup information and create the file, if necessary
    if [ ! -f "$FM_AUTOSETUP_PGSETUP" ]
      then
        fm_askserversetup
    fi

    # Import autosetup config files
    . "$FM_AUTOSETUP_PREFIXES"
    . "$FM_AUTOSETUP_PGSERVER"
    if [ "$(<"$FM_AUTOSETUP_PGSETUP")" = "" ]
      then
        FM_NOSETUP="1"
      else
        . "$FM_AUTOSETUP_PGSETUP"
    fi
    # Derive module user and database name from package and prefixes
    FM_PGDATABASE="${FM_PGDBPREFIX}_${FM_PGPKGNAME}"
    FM_PGUSER="${FM_PGUSERPREFIX}_${FM_PGPKGNAME}"
  else    
    # Set defaults
    FM_HEADLINE="$FM_PACKAGE"
    FM_PGDATABASE_DEFAULT="folio_${FM_PGPKGNAME}"
    FM_PGUSER_DEFAULT="folio_${FM_PGPKGNAME}"
    # Ask everything
    fm_askconf
    fm_askserver
    fm_askserversetup
fi

# Use a random string for an empty password
if [ "$FM_PGPASSWD" = "" ]
  then
    FM_PGPASSWD=$(</dev/urandom tr -dc 'A-Za-z0-9!#$%&()*+,-./:;<>?@[]^_`{|}~' | head -c 24)
  else
    # Strip forbidden characters to avoid problems
    FM_TEMPVAR=$(echo "$FM_PGPASSWD" | tr -dc 'A-Za-z0-9!#$%&()*+,-./:;<>?@[]^_`{|}~')
    # Message the user, if something had to be changed
    if [ "$FM_TEMPVAR" != "$FM_PGPASSWD" ]
      then
        echo "Your provided module password contained forbidden characters; was autocorrected."
    fi
    FM_PGPASSWD="$FM_TEMPVAR"
fi

# Write the settings to the environment file, setting it secure first
mkdir -p $(dirname "$FM_CONFIG")
touch "$FM_CONFIG"
# We don't know what exact name the user/group has, only that the user has the 
# full name in its description (workaround for overly long module names)
chown root:$(grep "FOLIO $FM_PACKAGE user" /etc/passwd | cut -d ":" -f "1" -s) "$FM_CONFIG"
chmod 640 "$FM_CONFIG"
echo "DB_HOST=$FM_PGSERVER
DB_PORT=$FM_PGPORT
DB_DATABASE=$FM_PGDATABASE
DB_USERNAME=$FM_PGUSER
DB_PASSWORD=$FM_PGPASSWD" > "$FM_CONFIG"

# Create pg_hba.conf entry
if [ -f "$FM_PGHBACONF" ]
  then
    # Try to find out the correct external IP address for the server
    FM_IP=$(ip a s | grep -oE "inet [0-9\.]+" | grep -v "inet 127" | head -n 1)
    echo "host    $FM_PGDATABASE    $FM_PGUSER    ${FM_IP:5}/32    md5" >> "$FM_PGHBACONF"
fi

if [ "$FM_NOSETUP" != "1" ]
  then
    # Do the setup
    if ! fm_serversetup
      then
        export NEWT_COLORS='root=,red'
        whiptail --title "$FM_PACKAGE - Server setup error" --msgbox \
          "Database setup ran into an error! Please check manually." 8 78
    fi
fi

# Remove temp file
rm -f "$FM_TEMP"

exit 0
